---
- name: getting NodeJS 6.x version
  shell: "curl -sL https://deb.nodesource.com/setup_6.x | sudo sh"

- name: Instaling NodeJS
  apt:
    pkg: nodejs
    state: latest

- name: Instaling Node Package Manager
  apt:
    pkg: npm
    state: latest
