---
#- name: Update apt
#  become: yes
#  apt: update_cache=yes

- name: Adding repository ondrej/php
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Install php7.1
  become: yes
  apt: pkg=php7.1 state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.1-cli
    - php7.1-fpm
    - php7.1-curl
    - php7.1-gd
    - php7.1-gmp
    - php7.1-imagick
    - php7.1-intl
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-redis
    - php7.1-xsl
    - php7.1-json
    - php7.1-tidy
    - php7.1-mbstring
  notify:
   - restart apache