---
- name: Adding repository for ruby brightbox/ruby-ng
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"

- name: Install ruby 2.x
  become: yes
  apt: pkg=ruby2.2 state=latest

- name: Install ruby 2.x-dev
  become: yes
  apt: pkg=ruby2.2-dev